### ISSUE TITLE
Species-selection issues

### ISSUE THREAD

**Issue by khanspers** [cytoscape/idmapper#20]
For some pathways, idmapper is guessing the wrong species, and then the necessary options for id mapping are not available. For example, a WikiPatways mouse pathway (WP1246, opened via WP app) is being recognized as human (main identifier is Entrez). When switching the Species drop-down to Mouse, only MGI is listed under "Map from", and is greyed out. Same goes for pathways in other species (rat etc).
<img width="552" alt="screen shot 2017-09-28 at 11 57 15 am" src="https://user-images.githubusercontent.com/1442197/30985594-903bb68c-a445-11e7-81ea-947fcd26cf7b.png">

**Comment by AlexanderPico** [comment]
Initial guess by app is correct (Entrez gene ids), but switching species results in losing this option (or any option) for "Map from"

**Comment by AlexanderPico** [comment]
We narrowed it down to here:

https://github.com/cytoscape/idmapper/blob/commandize/src/main/java/org/cytoscape/idmapper/internal/Species.java#L57

**Comment by AlexanderPico** [comment]
I'm getting an NPE with the latest version (with fixed getDefaultNodeTable)...

filteredStrings: [HGNC (e.g., DAPK1), Ensembl (e.g., ENSG00000139618), Entrez Gene (e.g., 11234), KEGG Genes (e.g., syn:ssr3451), miRBase (e.g., MIMAT0000001), UniGene (e.g., Hs.553708), Uniprot-TrEMBL (e.g., P62158)]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.cytoscape.idmapper.internal.MappingSource.patternMatch(MappingSource.java:118)
	at org.cytoscape.idmapper.internal.MappingSource.guessSource(MappingSource.java:138)
	at org.cytoscape.idmapper.task.ColumnMappingTask.guessSource(ColumnMappingTask.java:97)
	at org.cytoscape.idmapper.task.ColumnMappingTask.resetSpecies(ColumnMappingTask.java:85)
