### ISSUE TITLE
Failed to map Ensembl->SGD for galFiltered; HTTP 504 error

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#22]
1. Opened galFiltered
2. Right-clicked on name column
3. Select Map column
4. Guess was wrong
5. Set Yeast and Ensembl
6. Looooong wait then Message: Failed to map any...

504 Error Thrown:

java.io.IOException: HTTP error code : 504
	at org.cytoscape.idmapper.internal.BridgeDbIdMapper.post(BridgeDbIdMapper.java:216)
	at org.cytoscape.idmapper.internal.BridgeDbIdMapper.runQuery(BridgeDbIdMapper.java:247)
	at org.cytoscape.idmapper.internal.BridgeDbIdMapper.map(BridgeDbIdMapper.java:86)
	at org.cytoscape.idmapper.task.ColumnMappingTask.run(ColumnMappingTask.java:214)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:326)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AlexanderPico** [comment]
Confirmed that http://webservice.bridgedb.org was up and running. Not sure why a 504 timeout was returned...

**Comment by AlexanderPico** [comment]
Works from Gladstone today, no problem. Let's both test again from home.

**Comment by khanspers** [comment]
Maybe related: Running BridgeDb app using webservice.bridgedb.org/Human is problematic. Target ID Type (in destination type section) is blank.

**Comment by AdamStuart** [comment]
CNR
